### ISSUE TITLE
--geometry option not recognized

### ISSUE THREAD

**Issue by BluebirdGreycoat** [adrido/minetest-mapper-cpp#2]
Looks like the `--geometry` command-line option isn't recognized. Currently working around it using `--cornergeometry` instead.

I found this program after realizing that stock `minetestmapper` simply couldn't handle extremely large `postgres` worlds (30GB+), and I saw that this program had `--disable-blocklist-prefetch`, which looks to be a possible solution.

**Comment by adrido** [comment]
Oh looks like I missed something. If you want you can use the latest stable https://github.com/adrido/minetest-mapper-cpp/tree/v0.8.1
it should work there. Thanks for reporting. Ill fix it

**Comment by adrido** [comment]
Should be fixed by 456cfb7f0f67dccfd1402329a08c145ac59fb86f
